### ISSUE TITLE
Make Swipe stop?

### ISSUE THREAD

**Issue by abrajoe** [wdullaer/SwipeActionAdapter#11]
hey there!
would it be possible to define a swipe max? Like you can only swipe away half of the row? In addition, to keep the background and the row visible until I swipe back?

See Attachment :)
![16-04-_2015_21-30-05](https://cloud.githubusercontent.com/assets/829818/7189629/79a18fc8-e480-11e4-8df4-a44f42d928ba.png)

**Comment by wdullaer** [comment]
This is not as easy as it sounds.
It doesn't play very nice with the fact that you can have 2 swipe actions per direction.

It also has quite some impact on the backend code. I'm not sure if I can easily fit that in.

That's not to say I'll never implement it, but I think you'd better look for a library that already implements this if you want it on the short term.

**Comment by abrajoe** [comment]
Thank you very much. FYI: I came across this library, which exactly fitted on my needs https://github.com/baoyongzhang/SwipeMenuListView

**Comment by wdullaer** [comment]
Great stuff!

I'm happy you got your problem solved :-)
