### ISSUE TITLE
Combine SwipeActionListener and other touch events

### ISSUE THREAD

**Issue by gerlandiya** [wdullaer/SwipeActionAdapter#15]
Thank you for good swipe solution! Could you please help me with other event listeners: for my ListView I need your onSwipe method as well as single tap and long tap.
For instance only ListView scrolling works. If I use listview.setOnItemClickListener, swipe one doesnt' work anymore.

**Comment by wdullaer** [comment]
Two questions:
1. Are you using the latest version of the library?
2. Are you passing a reference of the ListView to the adapter? Without this it cannot properly set all the event listeners.

**Comment by gerlandiya** [comment]
I've updated version and now my onListItemClick works, thanks. The only question remaining is how to listen to long taps?

**Comment by wdullaer** [comment]
Just implement the standard ListView callback.
These type of questions are very generic though and belong more on stackoverflow rather than the issue page of this library.
