### ISSUE TITLE
Backward compatiblity (Nine Old Android ?)

### ISSUE THREAD

**Issue by babs** [wdullaer/SwipeActionAdapter#17]
Have you tried to use NineOldAndroid to make you libary backward compatible to lower than 4.0.0 ?

I've tried but it generates a bunch of glitches on old terminals :/

**Comment by wdullaer** [comment]
I do not intend to support versions of android smaller than 4.0
They're a negligible part of the market by now. I only have a limited amount of time to build these things, so I have to make choices. This seemed like a very obvious one.
