### ISSUE TITLE
Array adapter view is not refreshing after removal of string from content.

### ISSUE THREAD

**Issue by mikkysati** [wdullaer/SwipeActionAdapter#18]
Instead of content[] string, I made it as arraylist of string. On far left event, I am deleting that string from   the arraylist. The string gets deleted from the arraylist but the view of ListView is not refreshed event after calling notifyDataSetChanged() in both stringAdapter and mAdapter

**Comment by wdullaer** [comment]
There could be a million different things wrong with your code. For example are you sure you're manipulating the actual ArrayList rather than a deep copy of it?

I'm not having any issues with it. You'll have to come up with a code sample that allows me to reproduce this issue.

**Comment by mikkysati** [comment]
This is my code, modified version of your example: http://pastebin.com/7SnPrdz2

**Comment by wdullaer** [comment]
Try to use the remove method of the ArrayAdapter. I think that's actually keeping a copy of your data rather than a reference to it.

**Comment by mikkysati** [comment]
Ok. I replace 'list.remove(position)' with 'stringAdapter.remove(stringAdapter.getItem(position))', now the listView refreshes but if I swipe on row3, row4 gets deleted and if I use position-1, swipe on row5, row4 gets deleted.

**Comment by wdullaer** [comment]
The recommended pattern is to modify the ArrayList you're keeping in your application, clear the ArrayAdapter and then re-populate it with the modified ArrayList.

**Comment by mikkysati** [comment]
Check my pull request, it solved the problem. No need to re-populate ArrayAdapter.
