### ISSUE TITLE
Change background after swipe

### ISSUE THREAD

**Issue by hocgabri** [wdullaer/SwipeActionAdapter#20]
Is it possible to keep the "swiped background" until I swipe back?
 
For example: I would like to delete the row if I swipe to the right and show some extra information if I'm swiping to the left (until I swipe back). I couldn't find an easy implementation with the current library. 

Wouldn't it be make sense to pass this as an additional argument in the mAdapter.addBackground(...) function?
Thanks

**Comment by wdullaer** [comment]
That's not quite the way this library is meant to be used.
People with your request seem to have had success with this library: https://github.com/baoyongzhang/SwipeMenuListView
