### ISSUE TITLE
ListView.CHOICE_MODE_MULTIPLE_MODAL issue

### ISSUE THREAD

**Issue by leosimas** [wdullaer/SwipeActionAdapter#22]
I'm using the ListView.CHOICE_MODE_MULTIPLE_MODAL with AbsListView.MultiChoiceModeListener.

It works great, the items on the listview get checked on LongClick.

But when using it with the SwipeActionAdapter, the views don't change to the checked state although the onItemCheckedStateChanged is fired.

**Comment by wdullaer** [comment]
Do you mean that when you call `isChecked()` on your View it will always return false?

Also, can you check the view which is triggering `onItemCheckedStateChanged()` in the debugger?
My guess is that `onItemCheckedStateChanged()` is fired on the ViewGroup the library wraps your listitem in, but that the ViewGroup doesn't pass the checked state down.

**Comment by leosimas** [comment]
No, the listview returns the checked items.
My item view implements **android.widget.Checkable** but the **setChecked** is never called.
I just need to remove the SwipeActionAdapter and it works again.

**Comment by wdullaer** [comment]
The ListView interacts with a ViewGroup that wraps your View, so I can add the backgrounds and intercept the touches where needed.
This ViewGroup does not implement Checkable and does not pass setChecked on. I'm guessing that's the issue here. If it is, it should be relatively easy to fix.

**Comment by leosimas** [comment]
The pull request above worked for me :smile: 
Thanks for the tip @wdullaer
