### ISSUE TITLE
Listview background

### ISSUE THREAD

**Issue by Kostis4444** [wdullaer/SwipeActionAdapter#23]
Hi,
I have used a little bit that library, but I am unable to change the background colour of the listview(ie when it's empty i just have plain white) is there any way doing it, the way it is built with the row_bg.xml layouts for every item?
Thanks

**Comment by wdullaer** [comment]
The adapter shows your row layout.
You should make sure that the row layout you provide has the background you want.

**Comment by Kostis4444** [comment]
Thanks for the answer, however, the background of the row layout, just alters the colour of each row with items, and not the actual background on a list with empty items. 
ie:
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="horizontal" android:layout_width="match_parent"
    android:layout_height="?android:listPreferredItemHeight"
    android:background="@drawable/shape"   IF  YOU ARE TALKING ABOUT THAT BACKGROUND
    android:weightSum="1">
    <TextView
        android:id="@+id/text"
        android:layout_margin="8dp"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:gravity="center_vertical"
        android:textAppearance="?android:textAppearanceListItem"
        android:text="Dummy"
        android:textSize="15dp"
        android:autoText="false" />
</LinearLayout>

Thanks

**Comment by wdullaer** [comment]
Then set a background on your listview or one of it's parent layouts.
This adapter doesn't touch that. It just wraps individual items in your list.

**Comment by Kostis4444** [comment]
Thanks a lot , that seemed to work. I was not using a listview layout at all, and I thought it could be implemented otherwise from the rowlayout.
