### ISSUE TITLE
Different row layouts in one listview

### ISSUE THREAD

**Issue by Kostis4444** [wdullaer/SwipeActionAdapter#25]
Hi, another problem I was facing, and I am not sure if it is possible to be changed the way it is constructed, is if we can have multiple(different) row layouts according the the listview items. 
For example , just changing the background colour of an image of a row layout, according to a listview variable (as the adapter wraps the listview).
Thanks

**Comment by wdullaer** [comment]
In your adapter's onCreateView method you can inspect the item you are visualising and adapt your layout accordingly.
Be careful there though, ListView performance relies on reusing the already inflated row layouts, so if it's too radically different, there might be a penalty from inflating a new layout for each row.

This also something which is out of scope for this library. The reason it wraps around your adapter is to not limit your freedom in implementing the ListView you see fit.
