### ISSUE TITLE
List View with 2 different List Item heights

### ISSUE THREAD

**Issue by aherrick** [wdullaer/SwipeActionAdapter#26]
Hello,

I have a simple list view fragment that has 2 different items. First being the "section header" which separates my sections. Second being the actual list item content.

My list item "section header" height is set to wrap content, while I have a defined height (82dp) from the list item content.

I have two corresponding layout items (also at 82dp) that represent whats seen when swiping left and right. That works great.

However I'm something a strange bit of extra space (a couple of pixels) after my "section title" when the "addBackground" is applied to the swipe list view. If I remove it (the code below in particular) it doesn't include that extra space.

Is the issue issue due to the "section header"? I have code implemented so that swipe action does not occur on the section header.

Thanks!

                        .setSwipeActionListener(vbf)
                        .addBackground(SwipeDirections.DIRECTION_FAR_LEFT, R.layout.view_venue_beer_mark_blown)
                        .addBackground(SwipeDirections.DIRECTION_NORMAL_LEFT, R.layout.view_venue_beer_mark_blown)
                        .addBackground(SwipeDirections.DIRECTION_FAR_RIGHT, R.layout.view_venue_beer_mark_seen)
                        .addBackground(SwipeDirections.DIRECTION_NORMAL_RIGHT, R.layout.view_venue_beer_mark_seen)

**Comment by wdullaer** [comment]
The adapter wraps all your rows in a ViewGroup, so it can add the swipebackgrounds.
Your list headers, even if they return `false` on `hasActions()` will get these.
So if the headers are 60dp and the backgrounds 82dp, the header views will stretch up to 82dp.

I'm not sure what happens when you set the backgrounds to `match_parent`

Another thing I could do is make sure that the resulting view is the same dimensions as the view it's wrapping and truncating the backgrounds if necessary.

I need to experiment with this a bit.

**Comment by aherrick** [comment]
Hi @wdullaer thanks for the response.

I see what you mean... Yeah that seems like it makes sense to me to truncate if necessary. That would allow for the view to still wrap my view that is less height.

Could you go as far to have an API to determine exact which list views get wrapped in the first place?

Love the library!

**Comment by wdullaer** [comment]
I did some tests this morning and I'm not sure my previous assessment is entirely correct.
I don't manage to reproduce your problem.

What you can try is giving the background layouts a height of `match_parent` and see if that helps.

Another option is to use something like https://github.com/commonsguy/cwac-merge:
wrap the actual list items in the swipe adapter and use the MergeAdapter to add the headers

**Comment by wdullaer** [comment]
I really don't manage to reproduce this.
Can you show me the code you use to make the section headers?
