### ISSUE TITLE
Use Tick and Clock icon like Google inbox in left and right background layouts

### ISSUE THREAD

**Issue by rajazeeshanahmed** [wdullaer/SwipeActionAdapter#32]
I want to use the icons in the list-items background which display on swipe. I try to add the image in the background layout file but the image repeatedly draws so many times. Please tell me how can i add a icon with background color like in google inbox exactly? Thanks in advance!

**Comment by wdullaer** [comment]
to replicate the google inbox design, set the backgrounds to static and add the icons to your background resources.

**Comment by rajazeeshanahmed** [comment]
Yeah, I did the same as you said, and it is fixed. Thanks
