### ISSUE TITLE
SwipeActionAdapter 1.4.4 in 4.1 or 4.2 issues

### ISSUE THREAD

**Issue by MyateJx** [wdullaer/SwipeActionAdapter#33]
Hi , thanks for the SwipeActionAdapter, the app become more easier to use.

But, as shown in the figure, SwipeActionAdapter 1.4.4 may meet some trouble in showing in Android 4.1 or 4.2.

http://i3.tietuku.com/a07fe2e3f8fcf268.jpg

So, could it be fixed ?

**Comment by wdullaer** [comment]
what kind of cpu/gpu does this device have?
are you sure it is not running in some sort for powersaver mode?

**Comment by MyateJx** [comment]
@wdullaer Unfortunately, I think it may not because device but system.
Whether app runs in device or Genymotion, if the system is 4.1.2 or 4.2.2, it will show "maaaaaaaaaaaark" not "mark", while 4.3, 4.4, 5.1 is ok
Here is the figure of running situation in Genymotion:
http://i3.tietuku.com/45dc59a49a8ec257.jpg
