### ISSUE TITLE
Position issue on custom adapter.

### ISSUE THREAD

**Issue by wabsa** [wdullaer/SwipeActionAdapter#36]
Hi,
I really like this adapter but I have an issue with my custom adapter. What i wanna do is every swipe it juts increment the txtNumber (TextView) on current selected items. But what happened is some of the items also incrementing. attached is my current codes:

 public void onSwipe(int[] positionList, int[] directionList, ListView listView) {
        TextView selectedText;
        for(int i=0;i<positionList.length;i++) {
            int direction = directionList[i];
            int position = positionList[i];
            switch (direction) {
                case SwipeDirections.DIRECTION_FAR_LEFT:

                    selectedText = (TextView) getViewByPosition(position, listView).findViewById(R.id.txtNumber);
                    selectedText.setText(String.valueOf(Integer.parseInt(selectedText.getText().toString()) + 1));

                    break;

                case SwipeDirections.DIRECTION_FAR_RIGHT:

                    selectedText = (TextView) getViewByPosition(position,listView).findViewById(R.id.txtNumber);
                    if (Integer.parseInt(selectedText.getText().toString()) != 0) {
                        selectedText.setText(String.valueOf(Integer.parseInt(selectedText.getText().toString()) - 1));
                    }
                    break;

                default: break;
            }
            mAdapter.notifyDataSetChanged();
        }

    }

    public View getViewByPosition(int pos, ListView listView) {
        final int firstListItemPosition = listView.getFirstVisiblePosition();
        final int lastListItemPosition = firstListItemPosition + listView.getChildCount() - 1;

        if (pos < firstListItemPosition || pos > lastListItemPosition ) {
            return listView.getAdapter().getView(pos, null, listView);
        } else {
            final int childIndex = pos - firstListItemPosition;
            return listView.getChildAt(childIndex);
        }
    }
    public void convertStringToArray(String data) {
        JSONArray jsonArray = null;
        try {
            jsonArray = new JSONArray(data);

        } catch (JSONException e) {
            e.printStackTrace();
        }
        String[] strArr = new String[jsonArray.length()];
        ArrayList<String> arrayList = new ArrayList<String>();

        for (int i = 0; i < jsonArray.length(); i++) {
            try {

                strArr[i] = jsonArray.getJSONObject(i).getString("name");
                arrayList.add(jsonArray.getString(i));

                System.out.println(strArr[i]);

                ArrayAdapter<String> stringAdapter = new ArrayAdapter<String>(
                        this,
                        R.layout.foods_extra,
                        R.id.txtName,
                        new ArrayList<String>(Arrays.asList(strArr))
                );

                mAdapter = new SwipeActionAdapter(stringAdapter);
                mAdapter.setSwipeActionListener(this).setListView(getListView());

                mAdapter.addBackground(SwipeDirections.DIRECTION_FAR_LEFT, R.layout.row_bg_left)
                        .addBackground(SwipeDirections.DIRECTION_FAR_RIGHT, R.layout.row_bg_right);

                setListAdapter(mAdapter);
                stringAdapter.notifyDataSetChanged();

            } catch (JSONException e) {
                e.printStackTrace();
            }
        }
    }

Thanks, please help.

**Comment by wdullaer** [comment]
I'm sorry, but I don't think this is a specific issue with this library.

Feel free to reopen the issue if you can pinpoint this to a bug with this library.

In general StackExchange is a better place to post these kind of questions, you'll get a decent answer much faster there.
