### ISSUE TITLE
Request: Support for RecyclerView.

### ISSUE THREAD

**Issue by PsyGik** [wdullaer/SwipeActionAdapter#41]
This is a great library. Are there any plans to support RecyclerView?

**Comment by wdullaer** [comment]
RecyclerViews have a different method of interaction.
I haven't put in much time, but based on some quick searches, the approach I take in this library isn't really suited for RecyclerViews.
Combined with my current lack of time, it's unlikely that I'll support RecyclerViews.

I did find this link, which seems to suggest that more recent versions of the support library have basic swipe to dismiss functionality built in for RecyclerViews.
http://stackoverflow.com/questions/27293960/swipe-to-dismiss-for-recyclerview

**Comment by PsyGik** [comment]
Thanks for the update. I ended up implementing my own Adapter using RecyclerView's OnItemTouch Class. I'm closing this issue.
