### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by chiragandroid** [wdullaer/SwipeActionAdapter#42]
While i am importing this library in my project. it will give these errors NoClassDefFoundError ,i am using eclipse Mars 1.
 i have import library as a JAR.
[logTXT.txt](https://github.com/wdullaer/SwipeActionAdapter/files/70769/logTXT.txt)

**Comment by wdullaer** [comment]
Did you try a build clean?

**Comment by chiragandroid** [comment]
yES i HAVE TRIED CLEAN , BUILD.
please give ur email id ,so i can mail whole project

**Comment by wdullaer** [comment]
I'm not here to debug your project, and your last reply doesn't really tempt me into sacrificing my spare time to do you any favours.

The log indicates that the jar can't be found at runtime, so you have some sort of build error.
