### ISSUE TITLE
Have three textviews, and a image view, hence a custom listview

### ISSUE THREAD

**Issue by buryware** [wdullaer/SwipeActionAdapter#43]
We have four views, and when we drag right to left, we randomly  get a motion:CANCEL, and the swipe aborts.  Why?   Seems because we are leaving one view, and entering another.  Thanks.

**Comment by wdullaer** [comment]
Do any of your views react to scrolls or swipes as well?
As long as your views are static ones like textviews, buttons or (clipped) images, it should work properly.

**Comment by buryware** [comment]
Fixed, thanks!
