### ISSUE TITLE
Action Mode for listview not working properly when I use SwipeActionAdapter

### ISSUE THREAD

**Issue by alex-dokienko** [wdullaer/SwipeActionAdapter#44]
For my listview I have multiselect action mode, with following background selector for item layout

```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_activated="true" android:drawable="@color/md_grey_400"/>
    <item android:drawable="@android:color/transparent" />
</selector>
```

But when I've added SwipeActionAdapter, list item is not styled correctly on click (not become gray). I assume it's because my main layout not activated anymore.

Is there idea how to fix this, I would love to use this library in my project as it very easy to use and it gives what I need. Thanks for any help.

**Comment by wdullaer** [comment]
This library wraps your view in a `Viewgroup`.
The `Viewgroup` currently doesn't pass on its activated state.

This should be easy enough to fix.
