### ISSUE TITLE
Problem with static background

### ISSUE THREAD

**Issue by juliafriberg** [wdullaer/SwipeActionAdapter#47]
When fixed backgrounds is set to true (adapter.setFixedBackgrounds(true);), this happens:
![example1](https://cloud.githubusercontent.com/assets/3909369/14403694/cb7a34a2-fe61-11e5-840d-7182c066ffe6.gif)

When not, this happens:
![example2](https://cloud.githubusercontent.com/assets/3909369/14403698/de7d8518-fe61-11e5-8459-75af6ff686cb.gif)

Is it possible to combine them? To get the swiping in example 2 and the icons in example 1?

**Comment by wdullaer** [comment]
That is because your row has a transparent background.
Make sure that you explicitly set the background of your row to a solid color (white in this case).

**Comment by juliafriberg** [comment]
Thank you for your answer, that worked. Another problem occurs when using static backgrounds which does not happen when the backgrounds are non-static. I get this exception: java.lang.ClassCastException: android.widget.AbsListView$LayoutParams cannot be cast to android.view.ViewGroup$MarginLayoutParams.

**Comment by wdullaer** [comment]
Can you explain when you get this exception and maybe put the full stacktrace on a pastbin somewhere, so that I can have a look?

Are you manually setting layout parameters at some point?

**Comment by juliafriberg** [comment]
This exception occurs when I swipe right and want to start a new activity in onSwipe (I think). Here's the full stacktrace: http://pastebin.com/e7bzJgS8.  I do not set the layout parameters manually anywhere in the application.

**Comment by wdullaer** [comment]
The stacktrace doesn't contain a reference to this library, so my code isn't being called when this happens.
I'm guessing the exception happens when you release the swipe and the callback is fired. Maybe you're trying to do something fancy there?

**Comment by juliafriberg** [comment]
I am not doing anything different from when the background isn't static and then it works fine. The stacktrace doesn't reference my code either, which is confusing. If you don't know what the problem is I will simply have to try solving it on my own, thank you for the help anyway!

**Comment by juliafriberg** [comment]
I have tried removing all code from onSwipe() and I still get the same exception, and still only when fixed backgrounds is false. I can't figure out what is causing this, do you have any suggestions?

**Comment by wdullaer** [comment]
I'm sorry, but I have absolutely no idea.
In both cases all the views are part of the same `ViewGroup`. With translate backgrounds, they get translated off screen, while without they are just hidden.
If you can reproduce the issue on the sample app, I can take a closer look at it. 
Otherwise all I can say is that you should use the debugger to figure out exactly at which point it goes down (or try to simplify your code until it goes away, which should help you pinpoint the offending code).

**Comment by juliafriberg** [comment]
I managed to solve it by keeping a loop going through all objects and only calling adapter.notifyDataSetChanged() in the method onSwipe(). If i remove this it crashes. I have not tried it with the sample app and therefore do not know if the same thing occurs there.

**Comment by wdullaer** [comment]
It sounds like it's an issue with how you are managing your data in the adapter.
Potentially even a race condition, where you were trying to render something as you are removing it from the underlying adapter.

In any case I'm happy you managed to resolve it :-)
