### ISSUE TITLE
Align of elements in background row

### ISSUE THREAD

**Issue by CyberNyanta** [wdullaer/SwipeActionAdapter#55]
![image](https://cloud.githubusercontent.com/assets/10977301/19473479/8919d5da-9534-11e6-9588-2fe4e5810aa3.png)
I want to align  elements of background to left side(right swipe) or right side (left swipe). 
How can i do this?

**Comment by wdullaer** [comment]
https://github.com/wdullaer/SwipeActionAdapter#setfixedbackgroundsboolean-fixedbackgrounds

**Comment by CyberNyanta** [comment]
Thanks a lot!!!
